name: unique-workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Lengthy Task
        run: |
          echo "Starting lengthy task..."
          sleep 600 # Sleep for 10 minutes (600 seconds)
          echo "Lengthy task completed!"
